language: node_js
dist: trusty
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - sonar-scanner
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
notifications:
  email: false
addons:
  sonarcloud:
    organization: "mgaonach-github"
    projectKey: "mgaonach_FILA1-VideoChat-P2P"
    token: $SONAR_TOKEN